branches:
  only:
    - master

language: android
sudo: false

jdk:
  - oraclejdk8

android:
  components:
    - build-tools-25.0.1
    - android-25
    - doc-25
    - extra-android-support
    - extra-android-m2repository

before_install:
    - pip install --user codecov

script:
  - ./gradlew clean testDebugUnitTest jacocoTestReport --info

after_success:
  - ./gradlew coveralls
  - codecov
  - ./scripts/publish_snapshot.sh

cache:
  directories:
    - $HOME/.gradle
    - $HOME/.m2/repository
