branches:
  only:
    - master

language: android
sudo: false

android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.3
    - android-22
    - doc-23
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-google-google_play_services
    - addon-google_apis-google-28

before_install:
    - pip install --user codecov

script:
  - ./gradlew clean testDebugUnitTest jacocoTestReport --info

after_success:
  - ./gradlew coveralls
  - codecov
  - ./scripts/publish_snapshot.sh

cache:
  directories:
    - $HOME/.gradle
    - $HOME/.m2/repository
